name: e2e
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  e2e:
    name: E2E Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.21.0'
          check-latest: true

      - name: Check out code
        uses: actions/checkout@v3

      - name: Compose up
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: docker-compose.yml
          down-flags: "--volumes"
          services: |
            postgres
            mongo

      - name: Build
        run: |
          cp .env.example .env
          go build -o app

      - name: Run
        run: nohup ./app start &

      - name: E2E
        run: |
          npm i -g newman
          make e2e

    