name: e2e
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  e2e:
    name: E2E Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: realworld
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.21.0'
          check-latest: true

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build
        run: |
          cp .env.example .env
          go build -o app

      - name: Run
        run: nohup ./app start &

      - name: E2E
        run: |
          npm i -g newman
          make e2e

    