name: e2e
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: E2E Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: realworld
        ports:
          - 5432:5432

    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.21.0'
          check-latest: true

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build
        run: go build -o app

      - name: Run
        run: nohup ./app start &

      - name: E2E
        run: |
          sleep 5
          APIURL=http://0.0.0.0:5000 ./tests/run-api-tests.sh

    