name: test
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.21.0'
          check-latest: true

      - name: Compose up
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: docker-compose.yml
          down-flags: "--volumes"
          services: |
            postgres
            mongo

      - name: Check out code
        uses: actions/checkout@v3

      - name: Test
        run: make test